import { Fragment } from 'react';
import Sentence from './Sentence';
import './ReportBody.css';

export default function ReportBody({ report, reportLoading, reportError, activeSentId, onSentenceClick }) {
  // Error state
  if (reportError) {
    return (
      <div className="report-body">
        <div className="api-err">
          <strong>Report generation error</strong>
          {reportError}
          <br /><br />
          &middot; Is your server running at <strong>http://localhost:5000</strong>?<br />
          &middot; Is CORS enabled? (Flask: <code>from flask_cors import CORS; CORS(app)</code>)<br />
          &middot; Does your response include <code>report</code>?
        </div>
      </div>
    );
  }

  // Loading state
  if (reportLoading) {
    return (
      <div className="report-body">
        <div className="skel" style={{ width: '70%' }} />
        <div className="skel" style={{ width: '100%' }} />
        <div className="skel" style={{ width: '85%' }} />
        <div className="skel" style={{ width: '60%' }} />
        <div className="skel" style={{ width: '90%' }} />
        <div className="skel" style={{ width: '75%' }} />
      </div>
    );
  }

  // Empty state
  if (!report) {
    return (
      <div className="report-body">
        <div className="empty-st">
          <svg width="44" height="44" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1">
            <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
          </svg>
          <p>
            Open CONFIG &rarr; enter your endpoints &amp; HF token<br />
            Upload an image &rarr; Run Segmentation<br />
            Click Generate Report
          </p>
        </div>
      </div>
    );
  }

  // Report content
  return (
    <div className="report-body">
      {report.modality && (
        <div className="r-section">
          <div className="sec-label">Modality</div>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: '13px' }}>{report.modality}</span>
        </div>
      )}
      {report.sections.map((sec, i) => (
        <div key={i} className="r-section">
          <div className="sec-label">{sec.title}</div>
          <div>
            {sec.sentences.map((s) => (
              <Fragment key={s.id}>
                <Sentence
                  id={s.id}
                  text={s.text}
                  isActive={s.id === activeSentId}
                  onClick={(sentId) => onSentenceClick(sentId, s.text)}
                />{' '}
              </Fragment>
            ))}
          </div>
        </div>
      ))}
      <div className="disc">
        <strong>Disclaimer:</strong> This report was generated by an AI model and is for
        informational purposes only. It should not be used as a substitute for professional
        medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider.
      </div>
    </div>
  );
}
